# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0013_commoninfo2_student2_teacher2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commoninfo2',
            table='introduction_to_models_mit_commoninfo2',
        ),
        migrations.AlterModelTable(
            name='student2',
            table='introduction_to_models_mit_student2',
        ),
        migrations.AlterModelTable(
            name='teacher2',
            table='introduction_to_models_mti_teacher2',
        ),
    ]
