# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0017_auto_20170608_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
