# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0018_postlike_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
