# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0019_auto_20170608_0349'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postlike',
            table=None,
        ),
    ]
